### ISSUE TITLE
GRAPH.RO_QUERY Not being used when verison mistmatch causes refresh schema 

### ISSUE THREAD

**Issue by YaphetKG** [RedisGraph/redisgraph-py#103]
Hi @gkorland , Hi @swilly22 , Thanks for reviewing  #99 ... I was testing this new with a replica and I got into a similar issue. Where version mistmatch exception was causing the Graph._refresh_schema() which makes a procedure call, but this time with GRAPH.QUERY method

**Comment by swilly22** [comment]
#104 should resolve this issue.
