### ISSUE TITLE
Missing MERGE - ON CREATE SET, ON MATCH SET 

### ISSUE THREAD

**Issue by gomesian** [RedisGraph/redisgraph-py#120]
Love the Python library, but couldn't find arg options for using
MERGE with ON CREATE SET, ON MATCH SET functions.

https://oss.redislabs.com/redisgraph/commands/#merge

Seams to be be the best way to Bulk update..
Any plans to add? Or did I miss it somewhere...

eg.
MERGE (p:Person {name: 'Michael'}) 
ON CREATE SET p.created = 'timestamp', p.status = 'created', p.toreplace = 'replaceme'
ON MATCH SET p.lastupdated = 'timestamp2', p.status = 'updated', p.toreplace = 'replace'

**Comment by AvitalFineRedis** [comment]
@gomesian Try to use is the query string. It should work :)
