### ISSUE TITLE
support dict as a parameter value

### ISSUE THREAD

**Issue by swilly22** [RedisGraph/redisgraph-py#132]
```python
params = {'props': {'v2': 10}}
result = graph.query("MATCH (n) SET n = $props RETURN n", params)
```

Need to remove `'` from dict keys within `build_params_header` as Cypher doesn't expects dict keys to be wrapped in quotation marks.

**Comment by AvitalFineRedis** [comment]
@swilly22 Can you please write how the params in the example here look in the query?

**Comment by AvitalFineRedis** [comment]
`CYPHER props={v2:10} ` ?
