### ISSUE TITLE
Create Instagram like timeline using RedisGraph

### ISSUE THREAD

**Issue by amitsharma8891** [RedisGraph/redisgraph-py#14]
Hi,

I am creating a system where I need Instagram kind of timeline, where a user can create a post, can follow another user, and can like and share the posts. I wanted to create the aggregated timeline based on users activity on my post.

My requirements are:

1. Aggregated timeline (counts of like and share against that user e.g. Bryan and 10 other like this post)
2. If someone does any activity like, share than that post should come at top of my timeline

Please let me know if the above mentioned is possible? If yes how can I proceed (Any example)?

Or, am I asking too much to RedisGraph?

Any help would be highly appreciated.

Thanks

**Comment by CodifyIt** [comment]
@amitsharma8891 The mentioned requirements are possible, you design the nodes and their corresponding properties according to your needs for e.g consider a node for a post(label) and that has properties as ['creator', 'likes'] etc. and a node for a user(label) and they have a relation such as [:CREATES]. Everything depends on your implementation and design.
It is possible to create what you have mentioned in the requirement, but you have to work for it yourself.

P.S: Please close the issue as it is not specific to RedisGraph Library.
