### ISSUE TITLE
Edge cannot accept special character.

### ISSUE THREAD

**Issue by XufengXufengXufeng** [RedisGraph/redisgraph-py#25]
My project involves Chinese characters. I have no problem create nodes with Chinese naming. However, I am not able to create edge with Chinese naming. I have also tried special characters, such as '*','-', all won't work.

An example would be:

predicate = Edge(obj, '*', cont)
redis_graph.add_edge(predicate)
redis_graph.commit()

Is there a reason for this kind of behavior? Or am I doing it the wrong way?

Thank you.

**Comment by schwab** [comment]
I've seen a similar problem with utf-8 strings that have either ' or " in them.  Even delimiting them with \' or \" does not correct the issue. For this reason, I've had to pre-hash every string with md-5 hashes and store the delimited strings in redis cache as a hash datatapye.  This can be called with the hashed key and returned instead of the hashed value to callers.  Kinda a PITA, but it's an OK work around if  you can control all the calls into the graph with code to perform the hash lookup.

**Comment by psheltz** [comment]
I am receiving syntax errors like this on Node/Edge properties as well. I am using protocol buffers to encode objects as strings and placing them as properties. For example, consider a simple protobuf specification:
```
message Test1{
    string a = 1;
    string b = 2;
    string c = 3;
    string d = 4;
}
```
I can create the object in python with
`t = Test1(a='a',b='b',c='c',d='d')`
and serialize to a python `str` using:
`t.SerializeToString()`
`>> '\n\x01a\x12\x01b\x1a\x01c"\x01d' `
I build a Node with this serialized string as a property and commit:
```
n = Node(label='simple',properties={'proto':t.SerializeToString()})
graph.add_node(n)
graph.commit()
```
The commit fails stating: `ResponseError: Syntax error at offset 46 near 'd'`
My guess is that the serialization process added a `"` literal which is throwing off the parsing.

Are there any updates to the parser replacement? Thanks!

**Comment by swilly22** [comment]
Hi @psheltz, parser replacement has been in the workings for awhile now and should be ready within a number of 2-3 weeks.

**Comment by swilly22** [comment]
@psheltz, the parser has been replaced, you can find it on the current master branch or edge docker image.

**Comment by psheltz** [comment]
Excellent! Does this also require a working v1.99.1 RedisGraph?

**Comment by swilly22** [comment]
This will require installing redisgraph-py directly from github:
`pip install git+https://github.com/RedisGraph/redisgraph-py.git`

**Comment by jxf1002** [comment]
@swilly22 Does it work for Chinese characters already?
I've tried newest RedisGraph and redisgraph-py but get an error.
`redis.exceptions.ResponseError: errMsg: Invalid input '�': expected a property name line: 1, column: 43, offset: 42 errCtx: ...E (lqicohssma:person{name:"John Doe",年龄:33,gender:"male",status:"singl... errCtxOffset: 40`

**Comment by DvirDukhan** [comment]
@XufengXufengXufeng @schwab @psheltz 
I'm closing this issue. If you think it is still valid please re-open it.
