### ISSUE TITLE
flush swallows underlying exception

### ISSUE THREAD

**Issue by daniel-j-h** [RedisGraph/redisgraph-py#32]
The `.commit()` function can fail, e.g. due to a syntax error or internal problem. At the moment `.flush()` wraps the `.commit()` function but swallows all exceptions and simply prints a message:

https://github.com/RedisGraph/redisgraph-py/blob/c58c1b101f8d4c5d525149843cf0a2cd40708219/redisgraph/client.py#L138-L147

It wouldbe great if this Python client could properly propagate exceptions and also not print as a way to do error handling. Maybe we should use proper logging _if_ we need verbose runtime informaiton.

**Comment by swilly22** [comment]
@daniel-j-h Agree, I'll change this behavior soon
