### ISSUE TITLE
redis-graph 2.0 support

### ISSUE THREAD

**Issue by schwab** [RedisGraph/redisgraph-py#49]
Is there a commit with the changes to support the redis-graph 2.0 interface yet?  If not what's the plan to support the new result set format etc?

We are trying to plan when introduce the 2.0 code base and need to know what to expect from the python side of things.

**Comment by jeffreylovitz** [comment]
Hi @schwab ,

The master branch of `redisgraph-py` is entirely compatible with all of the latest RedisGraph features (new result set format, run-time error handling, array types, etc). It's actually the client we use for a lot of our automated testing!

There's not yet a release that includes all this, however. At the moment, you can get this support by installing like so:
`pip install git+https://github.com/RedisGraph/redisgraph-py.git@master`

**Comment by schwab** [comment]
Great... thanks!

**Comment by swilly22** [comment]
@schwab can we close this issue?
