### ISSUE TITLE
index out of range on node insert

### ISSUE THREAD

**Issue by jrozentur** [RedisGraph/redisgraph-py#63]
Installed an official docker of redisgraph, and latest redisgraph_py==1.7 from pypl. 
Inserting a single node fails on commit, because result does not have statistics (response[1]) - len(response) == 1:
(Pdb) response
[[b'Nodes created: 1', b'Query internal execution time: 0.548200 milliseconds']]

File "/orbital/base/user_service/src/py/v2/engine/redis_folder_graph.py", line 65, in add_folder
    g.commit()
  File "/opt/conda/lib/python3.6/site-packages/redisgraph/client.py", line 136, in commit
    return self.query(query)
  File "/opt/conda/lib/python3.6/site-packages/redisgraph/client.py", line 158, in query
    statistics = response[1]

**Comment by swilly22** [comment]
Hi @jrozentur,
Unfortunately for the time-being (until RedisGraph 2.0 is released) the official RedisGraph-py package (PYPI) isn't compatible with the latest docker image of RedisGraph, please install RedisGraph-py directly from github.

**Comment by DvirDukhan** [comment]
@jrozentur 
I'm closing this issue, as we are past the release of RedisGraph 2.0.
If you still encounter problems please re-open this issue.
