### ISSUE TITLE
python3 stat.decode() error

### ISSUE THREAD

**Issue by fdrong** [RedisGraph/redisgraph-py#64]
Traceback (most recent call last):
redisgraph/query_result.py", line 45, in _retrieve_data_from_statistics
    self.LABELS_ADDED: self._get_value(self.LABELS_ADDED, statistics),
  File "/redisgraph/query_result.py", line 57, in _get_value
    stat = stat.decode()
AttributeError: 'str' object has no attribute 'decode'

**Comment by swilly22** [comment]
Hi @fdrong, can you please share against which version of RedisGraph are you working?

**Comment by fdrong** [comment]
https://github.com/RediSearch/RediSearch  master version.
change it:
"/redisgraph/query_result.py", line 57, in _get_value
stat = stat.decode()
replace:
if isinstance(stat, bytes):
    stat = stat.decode()
it works

**Comment by swilly22** [comment]
I'm a bit confused you've referred to RediSearch in your link above, is that by mistake?

**Comment by DvirDukhan** [comment]
@fdrong 
I'm closing this issue. If you think that there is still an issue please re-open it.
