### ISSUE TITLE
unknown command `GRAPH.QUERY` failed

### ISSUE THREAD

**Issue by loveJasmine** [RedisGraph/redisgraph-py#85]
ub16_prj/redisLab % python demoGraph.py
Traceback (most recent call last):
  File "demoGraph.py", line 52, in <module>
    redis_graph.commit()
  File "/usr/local/lib/python3.8/site-packages/redisgraph/graph.py", line 96, in commit
    return self.query(query)
  File "/usr/local/lib/python3.8/site-packages/redisgraph/graph.py", line 130, in query
    response = self.redis_con.execute_command("GRAPH.QUERY", self.name, q, "--compact")
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: unknown command `GRAPH.QUERY`, with args beginning with: `social`, `CREATE (catkjxhxoe:person{name:"John Doe",age:33,gender:"male",status:"single"}),(omaaizblik:country{name:"Japan"}),(c`,

**Comment by DvirDukhan** [comment]
@loveJasmine 
Is the graph module loaded?

**Comment by loveJasmine** [comment]
yes, I forget load the module,

but it has another issue

**Comment by lucascassiano** [comment]
hi, thanks for making this lib. 

I'm with a similar issue, even tried a direct call to the docker image:
 
![image](https://user-images.githubusercontent.com/5508142/128584540-5662a102-eae9-46e3-96a5-8c5481fab4cf.png)

- running `redis-cli` inside the docker container. Everything seems fine
![image](https://user-images.githubusercontent.com/5508142/128584646-2c17eab1-a275-4a03-a12e-98b5d5b784b1.png)

However, on a python script running at the host machine, using this simple example (even without redisgraph-py) 
```py
import redis
from redisgraph import Node, Edge, Graph, Path

r = redis.Redis(host="0.0.0.0", port=6379)
reply = r.execute_command("GRAPH.QUERY MotoGP CREATE (:person {name:'lucas', age:27})")

print(reply)
```
I still get the error: 
```sh
redis.exceptions.ResponseError: unknown command `GRAPH.QUERY`, with args beginning with: `MotoGP`, `CREATE`, `(:person`, `{name:'lucas',`, `age:27})`, 
```

any idea of what is causing things?..
