### ISSUE TITLE
GRAPH.RO_QUERY Support

### ISSUE THREAD

**Issue by YaphetKG** [RedisGraph/redisgraph-py#99]
When trying to use this client in clustered env, can't seem to make it work on worker Redis nodes. Would be nice if there is some way to override GRAPH.QUERY. I think this relates to https://github.com/RedisGraph/RedisGraph/issues/343

**Comment by gkorland** [comment]
@YaphetKG are you trying to query a replica?

**Comment by YaphetKG** [comment]
Hi @gkorland , yes
